### ISSUE TITLE
BUG-0.0.10最新版本异常

### ISSUE THREAD

**Issue by DKuan** [awehook/vscode-blink-mind#3]
VScode版本 1.38.0
系统：windows10教育版，最近更新日期19-11-13
插件版本：0.0.9 正常显示，略有卡顿，功能正常
插件版本：0.0.10 主题切换正常，但是无节点显示，通过修改代码增加节点也无显示，通过右上角按钮也无法添加可以显示的tag。

**Comment by awehook** [comment]
谢谢你的反馈，可以按照下面的方法尝试一下：

1. 如果新建一张新的思维导图文档，看看功能是否正常
2. 如果新的思维导图文档功能正常，而打开原有的文档功能不正常，原因应该是由于新版本增加了主题功能和老版本生成的文件在格式上有了一点出入，可以点击TopicStyle面板下面的ClearAllCustomStyles 按钮，清除所有自定义样式，然后切换个主题，应该就可以正常显示了。

如果你尝试了上面的方法还是发现解决不了问题，可以将有问题的文件(如果没有个人隐私信息)发给我邮箱awehook@163.com, 我排查下问题

**Comment by DKuan** [comment]
VS code版本更新到最新的1.42.1可解决问题，新版本vscode的nodejs有一些更新。
